In [1]:
import sys
import os

# Add project root to Python path
sys.path.append(os.path.abspath(".."))

In [2]:
# ============================================
# 02 — PREPROCESSING & FEATURE ENGINEERING
# ============================================

import pandas as pd
import numpy as np

from src.data.load_data import load_dataset
from src.preprocessing.cleaning import clean_dataset
from src.preprocessing.feature_engineering import engineer_features
from src.preprocessing.encoding import encode_features
from src.preprocessing.scaling import scale_features

# --------------------------------------------
# 1. Load Raw Data
# --------------------------------------------

df = load_dataset("../data/raw/bank_transactions_data_2.csv")
df.head()

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,PreviousTransactionDate
0,TX000001,AC00128,14.09,2023-04-11 16:29:14,Debit,San Diego,D000380,162.198.218.92,M015,ATM,70,Doctor,81,1,5112.21,2024-11-04 08:08:08
1,TX000002,AC00455,376.24,2023-06-27 16:44:19,Debit,Houston,D000051,13.149.61.4,M052,ATM,68,Doctor,141,1,13758.91,2024-11-04 08:09:35
2,TX000003,AC00019,126.29,2023-07-10 18:16:08,Debit,Mesa,D000235,215.97.143.157,M009,Online,19,Student,56,1,1122.35,2024-11-04 08:07:04
3,TX000004,AC00070,184.50,2023-05-05 16:32:11,Debit,Raleigh,D000187,200.13.225.150,M002,Online,26,Student,25,1,8569.06,2024-11-04 08:09:06
4,TX000005,AC00411,13.45,2023-10-16 17:51:24,Credit,Atlanta,D000308,65.164.3.100,M091,Online,26,Student,198,1,7429.40,2024-11-04 08:06:39

In [3]:
# --------------------------------------------
# 2. Cleaning
# --------------------------------------------

df_clean = clean_dataset(df)
df_clean.head()

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,PreviousTransactionDate
0,TX000001,AC00128,14.09,2023-04-11 16:29:14,Debit,San Diego,D000380,162.198.218.92,M015,ATM,70,Doctor,81,1,5112.21,2024-11-04 08:08:08
1,TX000002,AC00455,376.24,2023-06-27 16:44:19,Debit,Houston,D000051,13.149.61.4,M052,ATM,68,Doctor,141,1,13758.91,2024-11-04 08:09:35
2,TX000003,AC00019,126.29,2023-07-10 18:16:08,Debit,Mesa,D000235,215.97.143.157,M009,Online,19,Student,56,1,1122.35,2024-11-04 08:07:04
3,TX000004,AC00070,184.50,2023-05-05 16:32:11,Debit,Raleigh,D000187,200.13.225.150,M002,Online,26,Student,25,1,8569.06,2024-11-04 08:09:06
4,TX000005,AC00411,13.45,2023-10-16 17:51:24,Credit,Atlanta,D000308,65.164.3.100,M091,Online,26,Student,198,1,7429.40,2024-11-04 08:06:39

In [4]:
# --------------------------------------------
# 3. Feature Engineering
# --------------------------------------------

df_feat = engineer_features(df_clean)
df_feat.head()

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,PreviousTransactionDate,TimeSincePrev,AmountBalanceRatio,LoginRisk,TransactionCount
0,TX000001,AC00128,14.09,2023-04-11 16:29:14,Debit,San Diego,D000380,162.198.218.92,M015,ATM,70,Doctor,81,1,5112.21,2024-11-04 08:08:08,-49477134.0,0.002756,0,1
1,TX000002,AC00455,376.24,2023-06-27 16:44:19,Debit,Houston,D000051,13.149.61.4,M052,ATM,68,Doctor,141,1,13758.91,2024-11-04 08:09:35,-42823516.0,0.027343,0,1
2,TX000003,AC00019,126.29,2023-07-10 18:16:08,Debit,Mesa,D000235,215.97.143.157,M009,Online,19,Student,56,1,1122.35,2024-11-04 08:07:04,-41694656.0,0.112423,0,1
3,TX000004,AC00070,184.50,2023-05-05 16:32:11,Debit,Raleigh,D000187,200.13.225.150,M002,Online,26,Student,25,1,8569.06,2024-11-04 08:09:06,-47403415.0,0.021528,0,1
4,TX000005,AC00411,13.45,2023-10-16 17:51:24,Credit,Atlanta,D000308,65.164.3.100,M091,Online,26,Student,198,1,7429.40,2024-11-04 08:06:39,-33228915.0,0.001810,0,1

In [5]:
# --------------------------------------------
# 4. Encoding Categorical Variables
# --------------------------------------------

df_encoded = encode_features(df_feat)
df_encoded.head()

,TransactionID,TransactionAmount,TransactionDate,CustomerAge,TransactionDuration,LoginAttempts,AccountBalance,PreviousTransactionDate,TimeSincePrev,AmountBalanceRatio,...,Channel_Branch,Channel_Online,CustomerOccupation_Engineer,CustomerOccupation_Retired,CustomerOccupation_Student,AccountID_freq,DeviceID_freq,IP Address_freq,MerchantID_freq,Location_freq
0,TX000001,14.09,2023-04-11 16:29:14,70,81,1,5112.21,2024-11-04 08:08:08,-49477134.0,0.002756,...,False,False,False,False,False,7,6,3,32,59
1,TX000002,376.24,2023-06-27 16:44:19,68,141,1,13758.91,2024-11-04 08:09:35,-42823516.0,0.027343,...,False,False,False,False,False,7,5,4,27,63
2,TX000003,126.29,2023-07-10 18:16:08,19,56,1,1122.35,2024-11-04 08:07:04,-41694656.0,0.112423,...,False,True,False,False,True,4,5,7,30,61
3,TX000004,184.50,2023-05-05 16:32:11,26,25,1,8569.06,2024-11-04 08:09:06,-47403415.0,0.021528,...,False,True,False,False,True,8,6,8,31,59
4,TX000005,13.45,2023-10-16 17:51:24,26,198,1,7429.40,2024-11-04 08:06:39,-33228915.0,0.001810,...,False,True,False,False,True,6,3,4,31,61

In [6]:
# --------------------------------------------
# 5. Scaling Numerical Features
# --------------------------------------------

df_scaled, scaler = scale_features(df_encoded)
df_scaled.head()

,TransactionID,TransactionAmount,TransactionDate,CustomerAge,TransactionDuration,LoginAttempts,AccountBalance,PreviousTransactionDate,TimeSincePrev,AmountBalanceRatio,...,Channel_Branch,Channel_Online,CustomerOccupation_Engineer,CustomerOccupation_Retired,CustomerOccupation_Student,AccountID_freq,DeviceID_freq,IP Address_freq,MerchantID_freq,Location_freq
0,TX000001,-0.971275,2023-04-11 16:29:14,1.423718,-0.552443,-0.206794,-0.000537,2024-11-04 08:08:08,-0.800762,-0.386493,...,False,False,False,False,False,0.394950,0.780834,-1.059021,1.141666,-0.028446
1,TX000002,0.269440,2023-06-27 16:44:19,1.311287,0.305314,-0.206794,2.216472,2024-11-04 08:09:35,-0.076706,-0.338188,...,False,False,False,False,False,0.394950,0.235683,-0.568379,0.168981,0.598373
2,TX000003,-0.586882,2023-07-10 18:16:08,-1.443277,-0.909842,-0.206794,-1.023534,2024-11-04 08:07:04,0.046138,-0.171040,...,False,True,False,False,True,-0.936152,0.235683,0.903547,0.752592,0.284963
3,TX000004,-0.387456,2023-05-05 16:32:11,-1.049768,-1.353017,-0.206794,0.885797,2024-11-04 08:09:06,-0.575097,-0.349611,...,False,True,False,False,True,0.838651,0.780834,1.394189,0.947129,-0.028446
4,TX000005,-0.973468,2023-10-16 17:51:24,-1.049768,1.120184,-0.206794,0.593589,2024-11-04 08:06:39,0.967391,-0.388350,...,False,True,False,False,True,-0.048751,-0.854621,-0.568379,0.947129,0.284963

In [7]:
# --------------------------------------------
# 6. Save Processed Data
# --------------------------------------------

df_clean.to_csv("../data/processed/cleaned.csv", index=False)
df_encoded.to_csv("../data/processed/encoded.csv", index=False)
df_scaled.to_csv("../data/processed/scaled.csv", index=False)

print("Phase 2 preprocessing completed successfully.")

Phase 2 preprocessing completed successfully.